In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family = font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

In [2]:
import urllib.request as req
# from urllib.error import HTTPError, URLError
import requests
from bs4 import BeautifulSoup

In [3]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

import time

In [4]:
import folium
import json

In [5]:
# from glob import glob

---

# 1. 불법 주 · 정차 단속실적

## (1) 데이터 처리

### 1) 데이터 로드

- 불법 주 · 정차 단속실적(서울특별시청) : 2022 기준
- https://news.seoul.go.kr/traffic/archives/35239
- 크롤링

In [6]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

page = urlopen("https://news.seoul.go.kr/traffic/archives/35239")
soup = BeautifulSoup(page, "html.parser")

In [7]:
post=soup.find("div", id="post_content")

In [8]:
violation_table = post.find_all("table")[0]

In [9]:
violation_tr=violation_table.find_all("tr")[3:]

gu_name =[]
cnt = []

for tr in violation_tr:
    p = tr.find_all("p")
    gu_name.append(p[0].text+"구")
    cnt.append(p[-1].text)

In [10]:
df = pd.DataFrame({"시군구":gu_name, "단속건수":cnt})

In [11]:
df.sort_values(by="단속건수", ascending=False)

     시군구     단속건수
5   동대문구   98,551
20   관악구   89,539
14   양천구   75,744
2    용산구   70,902
11   은평구   69,261
16   구로구   66,904
3    성동구   63,102
4    광진구   58,019
10   노원구   55,574
19   동작구   54,046
8    강북구   53,283
17   금천구   52,403
12  서대문구   52,186
9    도봉구   50,329
24   강동구   44,459
7    성북구   41,141
6    중랑구   38,434
22   강남구  192,211
0    종로구  162,739
1    중구구  155,137
15   강서구  145,065
21   서초구  141,181
23   송파구  126,284
18  영등포구  107,341
13   마포구  100,582

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군구     25 non-null     object
 1   단속건수    25 non-null     object
dtypes: object(2)
memory usage: 528.0+ bytes

In [13]:
df["단속건수"]=df["단속건수"].str.replace(",","").astype(float)

In [14]:
df["정규화"]=(df["단속건수"] - df["단속건수"].min())/(df["단속건수"].max() - df["단속건수"].min())

In [15]:
df.sort_values(by="정규화",ascending=False)

     시군구      단속건수       정규화
22   강남구  192211.0  1.000000
0    종로구  162739.0  0.808346
1    중구구  155137.0  0.758911
15   강서구  145065.0  0.693413
21   서초구  141181.0  0.668156
23   송파구  126284.0  0.571282
18  영등포구  107341.0  0.448097
13   마포구  100582.0  0.404144
5   동대문구   98551.0  0.390936
20   관악구   89539.0  0.332332
14   양천구   75744.0  0.242624
2    용산구   70902.0  0.211137
11   은평구   69261.0  0.200466
16   구로구   66904.0  0.185138
3    성동구   63102.0  0.160414
4    광진구   58019.0  0.127360
10   노원구   55574.0  0.111460
19   동작구   54046.0  0.101524
8    강북구   53283.0  0.096562
17   금천구   52403.0  0.090839
12  서대문구   52186.0  0.089428
9    도봉구   50329.0  0.077352
24   강동구   44459.0  0.039180
7    성북구   41141.0  0.017603
6    중랑구   38434.0  0.000000