In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name=fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf ").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"]=False

In [25]:
house = pd.read_csv("C:\kee\Mid\주택종류별+주택-+읍면동(연도+끝자리+0,5),+시군구(그+외+연도)_20230405113432.csv")
house.shape

(28, 6)

In [26]:
house

    동별(1)  동별(2)     2020   2020.1   2020.2   2020.3
0   동별(1)  동별(2)  종류별 주택수  종류별 주택수  종류별 주택수  종류별 주택수
1   동별(1)  동별(2)     단독주택     단독주택      아파트     연립주택
2   동별(1)  동별(2)       소계   일반단독주택       소계       소계
3     서울시    종로구    12259     6572    15688     5460
4     서울시     중구     5967     2266    26102     1944
5     서울시    용산구    14064     4941    37676     3969
6     서울시    성동구    10525     1947    67584     1990
7     서울시    광진구    15332      617    32135     4054
8     서울시   동대문구    17120     4344    65033     3274
9     서울시    중랑구    18560     1787    55499     4466
10    서울시    성북구    22520     9622    79206     6262
11    서울시    강북구    17557     4814    34733     4789
12    서울시    도봉구     8634     1412    65032     4144
13    서울시    노원구     6619     2132   163502     3448
14    서울시    은평구    14937     4223    59438     5830
15    서울시   서대문구    12600     2726    54132     5461
16    서울시    마포구    11618     2855    70307     3142
17    서울시    양천구     7698      617    90788     4042
18    서울시    강서구    10260     1230   113767     4794
19    서울시    구로구    11474     1563    83459     7388
20    서울시    금천구     8807      357    31689     3914
21    서울시   영등포구    14276     2107    74957     1487
22    서울시    동작구    14522     2565    61606     5289
23    서울시    관악구    21249     3564    55417     6218
24    서울시    서초구     5481      871    94499     5356
25    서울시    강남구     6968      839   126023     5827
26    서울시    송파구     8072      431   127239     4900
27    서울시    강동구     9956      509    87159     3114

In [27]:
house = house.drop(["동별(1)","2020"], axis=1)
house

    동별(2)   2020.1   2020.2   2020.3
0   동별(2)  종류별 주택수  종류별 주택수  종류별 주택수
1   동별(2)     단독주택      아파트     연립주택
2   동별(2)   일반단독주택       소계       소계
3     종로구     6572    15688     5460
4      중구     2266    26102     1944
5     용산구     4941    37676     3969
6     성동구     1947    67584     1990
7     광진구      617    32135     4054
8    동대문구     4344    65033     3274
9     중랑구     1787    55499     4466
10    성북구     9622    79206     6262
11    강북구     4814    34733     4789
12    도봉구     1412    65032     4144
13    노원구     2132   163502     3448
14    은평구     4223    59438     5830
15   서대문구     2726    54132     5461
16    마포구     2855    70307     3142
17    양천구      617    90788     4042
18    강서구     1230   113767     4794
19    구로구     1563    83459     7388
20    금천구      357    31689     3914
21   영등포구     2107    74957     1487
22    동작구     2565    61606     5289
23    관악구     3564    55417     6218
24    서초구      871    94499     5356
25    강남구      839   126023     5827
26    송파구      431   127239     4900
27    강동구      509    87159     3114

In [28]:
house = house.drop([0,1,2]).reset_index(drop=True)
house

   동별(2) 2020.1  2020.2 2020.3
0    종로구   6572   15688   5460
1     중구   2266   26102   1944
2    용산구   4941   37676   3969
3    성동구   1947   67584   1990
4    광진구    617   32135   4054
5   동대문구   4344   65033   3274
6    중랑구   1787   55499   4466
7    성북구   9622   79206   6262
8    강북구   4814   34733   4789
9    도봉구   1412   65032   4144
10   노원구   2132  163502   3448
11   은평구   4223   59438   5830
12  서대문구   2726   54132   5461
13   마포구   2855   70307   3142
14   양천구    617   90788   4042
15   강서구   1230  113767   4794
16   구로구   1563   83459   7388
17   금천구    357   31689   3914
18  영등포구   2107   74957   1487
19   동작구   2565   61606   5289
20   관악구   3564   55417   6218
21   서초구    871   94499   5356
22   강남구    839  126023   5827
23   송파구    431  127239   4900
24   강동구    509   87159   3114

In [29]:
house = house.rename(columns={'동별(2)': '구별', '2020.1': '단독주택', '2020.2':'아파트', '2020.3':'연립주택'})
house

      구별  단독주택     아파트  연립주택
0    종로구  6572   15688  5460
1     중구  2266   26102  1944
2    용산구  4941   37676  3969
3    성동구  1947   67584  1990
4    광진구   617   32135  4054
5   동대문구  4344   65033  3274
6    중랑구  1787   55499  4466
7    성북구  9622   79206  6262
8    강북구  4814   34733  4789
9    도봉구  1412   65032  4144
10   노원구  2132  163502  3448
11   은평구  4223   59438  5830
12  서대문구  2726   54132  5461
13   마포구  2855   70307  3142
14   양천구   617   90788  4042
15   강서구  1230  113767  4794
16   구로구  1563   83459  7388
17   금천구   357   31689  3914
18  영등포구  2107   74957  1487
19   동작구  2565   61606  5289
20   관악구  3564   55417  6218
21   서초구   871   94499  5356
22   강남구   839  126023  5827
23   송파구   431  127239  4900
24   강동구   509   87159  3114