In [23]:
import numpy as np
import pandas as pd

In [32]:
station=pd.read_csv('C:\\Users\\acorn\\Desktop\\오원석\\중간프로젝트\\광진구\\대중교통\\서울시 구별 지하철이용량(평균).csv')
station.round(0)

      구별   승차총승객수   하차총승객수     총승객수
0    강남구  19304.0  19939.0  39243.0
1    강동구   9945.0   9760.0  19704.0
2    강북구  22947.0  22560.0  45508.0
3    강서구  12977.0  12552.0  25529.0
4    관악구  30948.0  29883.0  60831.0
5    광진구  16129.0  15886.0  32015.0
6    구로구  16974.0  16989.0  33963.0
7    금천구  25051.0  26193.0  51244.0
8    노원구  12073.0  11779.0  23851.0
9    도봉구  17298.0  16778.0  34075.0
10  동대문구  10426.0  10420.0  20847.0
11   동작구  14362.0  14037.0  28399.0
12   마포구  12114.0  12482.0  24596.0
13  서대문구   7659.0   7676.0  15335.0
14   서초구  17011.0  17170.0  34181.0
15   성동구  10219.0  10378.0  20597.0
16   성북구   9957.0   9657.0  19615.0
17   송파구  10219.0  10242.0  20461.0
18   양천구  12326.0  12385.0  24711.0
19  영등포구  12746.0  13092.0  25838.0
20   용산구   8156.0   8410.0  16566.0
21   은평구  11669.0  11267.0  22936.0
22   종로구  17520.0  17594.0  35114.0
23    중구  12058.0  12311.0  24369.0
24   중랑구   9023.0   8768.0  17791.0

In [33]:
bike=pd.read_csv('C:\\Users\\acorn\\Desktop\\오원석\\중간프로젝트\\광진구\\대중교통\\서울시 구별 공공자전거 이용량(평균).csv')
bike

   대여소 그룹   대여 건수
0     강남구   804.0
1     강동구  1595.0
2     강북구  1082.0
3     강서구  2656.0
4     관악구  1714.0
5     광진구  2363.0
6     구로구  1565.0
7     금천구   963.0
8     노원구  1939.0
9     도봉구  1291.0
10   동대문구  1857.0
11    동작구  1309.0
12    마포구  1892.0
13   서대문구  1184.0
14    서초구   906.0
15    성동구  1833.0
16    성북구  1354.0
17    송파구  1903.0
18    양천구  2324.0
19   영등포구  2346.0
20    용산구  1076.0
21    은평구  1201.0
22    종로구  1309.0
23     중구  1106.0
24    중랑구  1306.0

In [34]:
transportation=pd.concat([station,bike],axis=1)
transportation.drop('대여소 그룹',axis=1,inplace=True)
transportation.rename(columns={'승차총승객수': '지하철 승차총승객수','하차총승객수':'지하철 하차총승객수','총승객수':'지하철 총승객수',
                              '대여 건수':'공공자전거 대여 건수'}, inplace=True)
transportation

      구별    지하철 승차총승객수    지하철 하차총승객수      지하철 총승객수  공공자전거 대여 건수
0    강남구  19304.142857  19938.857143  39242.904762        804.0
1    강동구   9944.642857   9759.642857  19704.142857       1595.0
2    강북구  22947.000000  22560.333333  45507.666667       1082.0
3    강서구  12976.888889  12552.111111  25529.222222       2656.0
4    관악구  30948.250000  29882.750000  60831.250000       1714.0
5    광진구  16128.909091  15885.636364  32014.636364       2363.0
6    구로구  16973.750000  16989.375000  33963.125000       1565.0
7    금천구  25051.000000  26193.000000  51244.000000        963.0
8    노원구  12072.538462  11778.692308  23851.384615       1939.0
9    도봉구  17297.666667  16777.666667  34075.000000       1291.0
10  동대문구  10426.333333  10420.333333  20846.666667       1857.0
11   동작구  14362.083333  14036.583333  28398.750000       1309.0
12   마포구  12114.437500  12481.500000  24595.812500       1892.0
13  서대문구   7659.200000   7676.000000  15335.400000       1184.0
14   서초구  17011.166667  17169.916667  34181.333333        906.0
15   성동구  10219.285714  10377.785714  20596.928571       1833.0
16   성북구   9957.333333   9657.222222  19614.555556       1354.0
17   송파구  10218.851852  10241.777778  20460.740741       1903.0
18   양천구  12325.600000  12385.000000  24710.800000       2324.0
19  영등포구  12745.916667  13092.000000  25837.833333       2346.0
20   용산구   8156.000000   8409.888889  16566.000000       1076.0
21   은평구  11668.846154  11266.769231  22935.846154       1201.0
22   종로구  17520.000000  17593.928571  35114.142857       1309.0
23    중구  12057.900000  12311.150000  24369.150000       1106.0
24   중랑구   9023.125000   8767.750000  17790.750000       1306.0

In [35]:
transportation['대중교통 총이용량'] = transportation['지하철 총승객수'] + transportation['공공자전거 대여 건수']

In [36]:
transportation.round()

      구별  지하철 승차총승객수  지하철 하차총승객수  지하철 총승객수  공공자전거 대여 건수  대중교통 총이용량
0    강남구     19304.0     19939.0   39243.0        804.0    40047.0
1    강동구      9945.0      9760.0   19704.0       1595.0    21299.0
2    강북구     22947.0     22560.0   45508.0       1082.0    46590.0
3    강서구     12977.0     12552.0   25529.0       2656.0    28185.0
4    관악구     30948.0     29883.0   60831.0       1714.0    62545.0
5    광진구     16129.0     15886.0   32015.0       2363.0    34378.0
6    구로구     16974.0     16989.0   33963.0       1565.0    35528.0
7    금천구     25051.0     26193.0   51244.0        963.0    52207.0
8    노원구     12073.0     11779.0   23851.0       1939.0    25790.0
9    도봉구     17298.0     16778.0   34075.0       1291.0    35366.0
10  동대문구     10426.0     10420.0   20847.0       1857.0    22704.0
11   동작구     14362.0     14037.0   28399.0       1309.0    29708.0
12   마포구     12114.0     12482.0   24596.0       1892.0    26488.0
13  서대문구      7659.0      7676.0   15335.0       1184.0    16519.0
14   서초구     17011.0     17170.0   34181.0        906.0    35087.0
15   성동구     10219.0     10378.0   20597.0       1833.0    22430.0
16   성북구      9957.0      9657.0   19615.0       1354.0    20969.0
17   송파구     10219.0     10242.0   20461.0       1903.0    22364.0
18   양천구     12326.0     12385.0   24711.0       2324.0    27035.0
19  영등포구     12746.0     13092.0   25838.0       2346.0    28184.0
20   용산구      8156.0      8410.0   16566.0       1076.0    17642.0
21   은평구     11669.0     11267.0   22936.0       1201.0    24137.0
22   종로구     17520.0     17594.0   35114.0       1309.0    36423.0
23    중구     12058.0     12311.0   24369.0       1106.0    25475.0
24   중랑구      9023.0      8768.0   17791.0       1306.0    19097.0

In [37]:
transportation.round().sort_values(by='대중교통 총이용량',ascending=False)

      구별  지하철 승차총승객수  지하철 하차총승객수  지하철 총승객수  공공자전거 대여 건수  대중교통 총이용량
4    관악구     30948.0     29883.0   60831.0       1714.0    62545.0
7    금천구     25051.0     26193.0   51244.0        963.0    52207.0
2    강북구     22947.0     22560.0   45508.0       1082.0    46590.0
0    강남구     19304.0     19939.0   39243.0        804.0    40047.0
22   종로구     17520.0     17594.0   35114.0       1309.0    36423.0
6    구로구     16974.0     16989.0   33963.0       1565.0    35528.0
9    도봉구     17298.0     16778.0   34075.0       1291.0    35366.0
14   서초구     17011.0     17170.0   34181.0        906.0    35087.0
5    광진구     16129.0     15886.0   32015.0       2363.0    34378.0
11   동작구     14362.0     14037.0   28399.0       1309.0    29708.0
3    강서구     12977.0     12552.0   25529.0       2656.0    28185.0
19  영등포구     12746.0     13092.0   25838.0       2346.0    28184.0
18   양천구     12326.0     12385.0   24711.0       2324.0    27035.0
12   마포구     12114.0     12482.0   24596.0       1892.0    26488.0
8    노원구     12073.0     11779.0   23851.0       1939.0    25790.0
23    중구     12058.0     12311.0   24369.0       1106.0    25475.0
21   은평구     11669.0     11267.0   22936.0       1201.0    24137.0
10  동대문구     10426.0     10420.0   20847.0       1857.0    22704.0
15   성동구     10219.0     10378.0   20597.0       1833.0    22430.0
17   송파구     10219.0     10242.0   20461.0       1903.0    22364.0
1    강동구      9945.0      9760.0   19704.0       1595.0    21299.0
16   성북구      9957.0      9657.0   19615.0       1354.0    20969.0
24   중랑구      9023.0      8768.0   17791.0       1306.0    19097.0
20   용산구      8156.0      8410.0   16566.0       1076.0    17642.0
13  서대문구      7659.0      7676.0   15335.0       1184.0    16519.0