In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv',encoding='cp949')
df.head()

In [ ]:
times = []
for i in range(24):
  a = str(i).zfill(2)
  b = str(i+1).zfill(2)
  times.append('{}시-{}시'.format(a,b))

In [ ]:
for time in times:
  df[time + ' 승하차 인원'] = df[time + ' 승차인원']+df[time + ' 하차인원']

In [ ]:
df2=df.drop(df.columns[3:52],axis=1)
df2

In [13]:
df3=df2.drop('사용월',axis=1).groupby(['호선명','지하철역']).mean().round(0)
df3.head()

                00시-01시 승하차 인원  01시-02시 승하차 인원  02시-03시 승하차 인원  \
호선명 지하철역
2호선 강변                 14796.0           144.0             4.0
    강변(동서울터미널)          7836.0           134.0             7.0
    건대입구               20348.0          1024.0            19.0
    구의                 11818.0           144.0             4.0
    구의(광진구청)            7528.0           144.0             6.0

                03시-04시 승하차 인원  04시-05시 승하차 인원  05시-06시 승하차 인원  \
호선명 지하철역
2호선 강변                     0.0            54.0         15610.0
    강변(동서울터미널)             1.0            28.0         12360.0
    건대입구                   2.0           363.0         21183.0
    구의                     0.0            29.0         15101.0
    구의(광진구청)               1.0            37.0         14482.0

                06시-07시 승하차 인원  07시-08시 승하차 인원  08시-09시 승하차 인원  \
호선명 지하철역
2호선 강변                 74061.0        155271.0        229213.0
    강변(동서울터미널)         55383.0        118099.0        178562.0
    건대입구               42979.0         87995.0        171785.0
    구의                 39456.0         90753.0        163148.0
    구의(광진구청)           36730.0         82503.0        152606.0

                09시-10시 승하차 인원  ...  14시-15시 승하차 인원  15시-16시 승하차 인원  \
호선명 지하철역                        ...
2호선 강변                180077.0  ...        168995.0        180030.0
    강변(동서울터미널)        140875.0  ...        122252.0        132292.0
    건대입구              120832.0  ...        122598.0        132727.0
    구의                 98159.0  ...         65039.0         69952.0
    구의(광진구청)           90618.0  ...         55997.0         61826.0

                16시-17시 승하차 인원  17시-18시 승하차 인원  18시-19시 승하차 인원  \
호선명 지하철역
2호선 강변                193446.0        215184.0        257294.0
    강변(동서울터미널)        143132.0        163612.0        206687.0
    건대입구              153171.0        193268.0        264014.0
    구의                 75532.0         91217.0        127730.0
    구의(광진구청)           70729.0         87966.0        129647.0

                19시-20시 승하차 인원  20시-21시 승하차 인원  21시-22시 승하차 인원  \
호선명 지하철역
2호선 강변                230419.0        173513.0        154795.0
    강변(동서울터미널)        164244.0        118970.0        103919.0
    건대입구              213038.0        156550.0        160101.0
    구의                103804.0         73438.0         70084.0
    구의(광진구청)           93590.0         63936.0         62297.0

                22시-23시 승하차 인원  23시-24시 승하차 인원
호선명 지하철역
2호선 강변                135586.0         69352.0
    강변(동서울터미널)         86864.0         41614.0
    건대입구              153809.0         91416.0
    구의                 68678.0         39540.0
    구의(광진구청)           57708.0         31775.0

[5 rows x 24 columns]